# Generated by Django 3.0.5 on 2020-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Surname', models.CharField(max_length=100, null=True)),
                ('Type', models.CharField(choices=[('Singer', 'Singer'), ('Intrumentalist', 'Instrumentalist'), ('DJ', 'DJ'), ('Dancer', 'Dancer'), ('Other', 'Other')], max_length=100, null=True)),
                ('Instrument', models.CharField(max_length=100, null=True)),
                ('NIE', models.CharField(max_length=100, null=True)),
                ('N_Price', models.FloatField(null=True)),
                ('B_Price', models.FloatField(null=True)),
                ('IRPF', models.FloatField(null=True)),
                ('Agency', models.CharField(choices=[('THM', 'THM'), ('AUTONOMO', 'AUTONOMO')], max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
