# Generated by Django 3.0.5 on 2020-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0002_artist_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Type',
        ),
        migrations.AddField(
            model_name='artist',
            name='Types',
            field=models.ManyToManyField(to='lineup.Type'),
        ),
    ]
