# Generated by Django 3.0.5 on 2020-05-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0003_auto_20200501_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ArtistType',
        ),
    ]
