# Generated by Django 3.0.5 on 2020-05-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0004_auto_20200501_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Instrument',
        ),
    ]
