# Generated by Django 3.0.5 on 2020-05-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0005_remove_artist_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='Artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup.Artist'),
        ),
        migrations.AddField(
            model_name='show',
            name='Time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='Place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup.Place'),
        ),
    ]
