# Generated by Django 3.0.5 on 2020-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0009_auto_20200502_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
