# Generated by Django 3.0.5 on 2020-05-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0010_auto_20200502_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='Gender',
        ),
    ]
