# Generated by Django 3.0.5 on 2020-05-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0011_remove_artist_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='Gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup.Gender'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='Agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup.Agency'),
        ),
    ]
