# Generated by Django 3.0.5 on 2020-05-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0012_auto_20200502_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='Gender',
            new_name='Agency',
        ),
    ]
