# Generated by Django 3.0.5 on 2020-05-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0013_auto_20200502_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='Name',
        ),
        migrations.AddField(
            model_name='event',
            name='Artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup.Artist'),
        ),
        migrations.AddField(
            model_name='event',
            name='Place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup.Place'),
        ),
        migrations.AddField(
            model_name='event',
            name='EventName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineup.EventName'),
        ),
    ]
