# Generated by Django 3.0.5 on 2020-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0014_auto_20200502_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventAV',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='ShowAV',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
