# Generated by Django 3.0.5 on 2020-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0015_auto_20200502_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='ShowAV',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
