# Generated by Django 3.0.5 on 2020-05-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0017_auto_20200502_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='Event',
        ),
        migrations.AddField(
            model_name='show',
            name='From',
            field=models.TimeField(null=True),
        ),
    ]
