# Generated by Django 3.0.5 on 2020-05-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0019_auto_20200502_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='Nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
