# Generated by Django 3.0.5 on 2020-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0020_artist_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventAV',
        ),
        migrations.AddField(
            model_name='event',
            name='EventNames',
            field=models.CharField(choices=[('CandyRock', 'CandyRock'), ('RockSunset', 'RockSunset'), ('UrbanSunset', 'UrbanSunset'), ('CountrySunset', 'CountrySunset'), ('ReggaeSunset', 'ReggaeSunset'), ('Gynburger', 'Gynburger')], max_length=50, null=True),
        ),
    ]
