# Generated by Django 3.0.5 on 2020-05-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0022_show_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventNames',
        ),
        migrations.RemoveField(
            model_name='show',
            name='ShowAV',
        ),
    ]
