# Generated by Django 3.0.5 on 2020-05-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0023_auto_20200502_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='Types',
        ),
        migrations.AlterField(
            model_name='artist',
            name='NIE',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ArtistType',
        ),
        migrations.AddField(
            model_name='artist',
            name='Instruments',
            field=models.ManyToManyField(to='lineup.Instrument'),
        ),
    ]
