# Generated by Django 3.0.5 on 2020-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0025_auto_20200506_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='B_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='N_Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
